### ISSUE TITLE
Clicked element is now shown active

### ISSUE THREAD

**Issue by PrajapatiDhara1510** [cdpawar08/slidertodropdown#2]
Hello,

When i click on any item from slider it doesn't get active. Only default element is remains active.

**Comment by cdpawar08** [comment]
Hi

Here i have only display the active item design. developer can manage this class as per their functionality.

Thank You

**Comment by PrajapatiDhara1510** [comment]
Hello @cdpawar08  i did not get updated files.

**Comment by cdpawar08** [comment]
Hi

@dhara15101991 please check my above comment.
